# Generated by Django 6.0.4 on 2026-05-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudFinanciamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.BigIntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('ingresos_personal', models.FloatField()),
                ('garante_nombre', models.CharField(max_length=100)),
                ('ingresos_garante', models.FloatField()),
                ('edad_garante', models.IntegerField()),
                ('garante_tipo_trabajo', models.CharField(max_length=20)),
                ('garante_antiguedad', models.IntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('precio_base', models.FloatField()),
                ('plan', models.CharField(max_length=20)),
                ('cuotas_cantidad', models.IntegerField()),
                ('cuota_mensual', models.FloatField()),
                ('importe_adjudicacion', models.FloatField()),
                ('gastos_retiro', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
